#!/usr/bin/env bash

HEROKU_EMAIL=""
HEROKU_API_KEY=""
HEROKU_APP_NAME="chiu-frontend"

terraform apply \
    -auto-approve \
    -var heroku_email="$HEROKU_EMAIL" \
    -var heroku_api_key="$HEROKU_API_KEY" \
    -var heroku_app_name="$HEROKU_APP_NAME" \
